// <auto-generated>MC 社群高频术语本地词典:离线秒翻,不依赖网络与第三方翻译限额。
// 收录模组/加载器/玩法社区已形成共识的中文译名(如 Sodium→钠, Create→机械动力)。
// 词典未命中时才走网络翻译(MyMemory 失败 → Google 免费端点兜底)。</auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace FufuLauncher.Next.UI;

/// <summary>英文→中文本地词典 + 双源网络翻译兜底。静态无状态,UI 各 Deck 共享。</summary>
internal static class ZhDict
{
    // 按原文精确匹配(大小写不敏感)。模组/加载器/玩法高频术语。
    private static readonly Dictionary<string, string> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        // ---- 性能优化(用户点名:钠/锂在社区已习惯) ----
        ["Sodium"] = "钠(区块渲染性能优化)",
        ["Lithium"] = "锂(实体与方块运算优化)",
        ["OptiFine"] = "光影优化(OptiFine)",
        ["Iris"] = "光影加载器(Iris)",
        ["Iris Shaders"] = "光影加载器(Iris)",
        ["Phosphor"] = "磷(光照引擎优化)",
        ["FerriteCore"] = "铁氧体核心(内存优化)",
        ["Starlight"] = "星光(光照引擎重写)",
        ["Entity Culling"] = "实体剔除(性能优化)",
        ["Krypton"] = "氪(网络协议优化)",
        ["C2ME"] = "区块加载优化(C2ME)",

        // ---- 物品/界面 ----
        ["JEI"] = "物品管理器(JEI)",
        ["Just Enough Items"] = "物品管理器(JEI)",
        ["REI"] = "物品管理器(REI)",
        ["Roughly Enough Items"] = "物品管理器(REI)",
        ["EMI"] = "物品管理器(EMI)",
        ["AppleSkin"] = "苹果皮(饱食度显示)",
        ["Inventory Tweaks"] = "背包整理",
        ["Mouse Tweaks"] = "鼠标手势优化",
        ["Xaero's Minimap"] = "Xaero的小地图",
        ["Xaero's World Map"] = "Xaero的世界地图",
        ["JourneyMap"] = "旅行地图",
        ["Waystones"] = "传送石碑",
        ["Iron Chests"] = "更多箱子",
        ["Storage Drawers"] = "存储抽屉",
        ["Chisel"] = "凿子(方块装饰)",
        ["Quark"] = "夸克(原版增强)",
        ["GraveStone"] = "死亡墓碑",
        ["TrashSlot"] = "垃圾桶",
        ["Controlling"] = "按键冲突管理",

        // ---- 内容/冒险 ----
        ["Create"] = "机械动力",
        ["Tinkers Construct"] = "匠魂",
        ["Twilight Forest"] = "暮色森林",
        ["The Aether"] = "天境",
        ["Aether II"] = "天境II",
        ["Biomes O' Plenty"] = "超多生物群系",
        ["Oh The Biomes You'll Go"] = "你将去的生物群系",
        ["Terralith"] = "地形扩展(Terralith)",
        ["Alex's Mobs"] = "Alex的生物",
        ["Mowzie's Mobs"] = "Mowzie的生物",
        ["Ice and Fire"] = "冰与火之歌",
        ["Apotheosis"] = "神话附魔(Apotheosis)",
        ["Botania"] = "植物魔法",
        ["Thaumcraft"] = "神秘时代",
        ["Blood Magic"] = "血魔法",
        ["Astral Sorcery"] = "星辉魔法",
        ["Ars Nouveau"] = "新生魔艺",
        ["Mekanism"] = "通用机械",
        ["Industrial Craft"] = "工业时代",
        ["Thermal Expansion"] = "热力膨胀",
        ["Immersive Engineering"] = "沉浸工程",
        ["EnderIO"] = "末地接口(EnderIO)",
        ["Applied Energistics"] = "应用能源(AE)",
        ["Refined Storage"] = "精致存储",
        ["Farmer's Delight"] = "农夫乐事",
        ["Pam's HarvestCraft"] = "潘马斯农场",
        ["Serene Seasons"] = "安逸季节",
        ["Dungeons Arise"] = "地牢崛起",
        ["Cataclysm"] = "灾厄(Cataclysm)",
        ["The End of Herobrine"] = "Herobrine的终结",
        ["Blue Skies"] = "蓝天传说",

        // ---- 前置/工具 ----
        ["Fabric API"] = "Fabric前置(Fabric API)",
        ["Cloth Config"] = "配置界面前置(Cloth)",
        ["Architectury"] = "跨平台前置(Architectury)",
        ["GeckoLib"] = "动画前置(GeckoLib)",
        ["CoroUtil"] = "通用前置(CoroUtil)",
        ["Patchouli"] = "帕秋莉手册(前置)",
        ["Bookshelf"] = "书架(前置)",
        ["Curios"] = "饰品栏(Curios)",
        ["Trinkets"] = "饰品栏(Trinkets)",
        ["Pehkui"] = "尺寸缩放(Pehkui)",
        ["KubeJS"] = "KubeJS(脚本)",
        ["CraftTweaker"] = "合成修改器",
        ["Just Enough Resources"] = "足够资源(JER)",
        ["Dynmap"] = "网页地图(Dynmap)",
        ["WorldEdit"] = "创世神(WE)",
        ["WorldGuard"] = "创世神区域保护(WG)",
        ["EssentialsX"] = "基础插件(EssentialsX)",
        ["Lucky Block"] = "幸运方块",
        ["CustomNPC"] = "自定义NPC",
        ["OpenComputers"] = "开放式电脑",
        ["ComputerCraft"] = "电脑工艺(CC)",
        ["ProjectE"] = "等价交换",
        ["Project MMO"] = "项目MMO",
    };

    /// <summary>词典命中返回 true。整句长文本(简介)也做逐词替换尝试,命中任一即返回替换结果。</summary>
    public static bool TryLookup(string en, out string zh)
    {
        if (string.IsNullOrWhiteSpace(en)) { zh = ""; return false; }
        if (Map.TryGetValue(en.Trim(), out var hit) && hit != null) { zh = hit; return true; }   // 2026-09-25:TryGetValue 失败时 out 可 null,判空后赋值消 CS8601
        // 长句:词典词出现在原文中,做原位替换(保留其余英文,帮助理解)
        string s = en.Trim();
        bool any = false;
        foreach (var kv in Map)
        {
            if (s.Contains(kv.Key, StringComparison.OrdinalIgnoreCase))
            {
                s = Regex.Replace(s, Regex.Escape(kv.Key), kv.Value, RegexOptions.IgnoreCase);
                any = true;
            }
        }
        zh = any ? s : "";
        return any;
    }

    /// <summary>Google 免费翻译端点(无需 key,国内可达):失败返回 null。</summary>
    public static async Task<string?> TranslateViaGoogleAsync(HttpClient http, string en)
    {
        try
        {
            string url = "https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q="
                         + Uri.EscapeDataString(en);
            var json = await http.GetStringAsync(url);
            using var doc = System.Text.Json.JsonDocument.Parse(json);
            var sb = new System.Text.StringBuilder();
            if (doc.RootElement.ValueKind == System.Text.Json.JsonValueKind.Array)
            {
                foreach (var seg in doc.RootElement[0].EnumerateArray())
                {
                    if (seg.ValueKind == System.Text.Json.JsonValueKind.Array && seg[0].ValueKind == System.Text.Json.JsonValueKind.String)
                        sb.Append(seg[0].GetString());
                }
            }
            var zh = sb.ToString().Trim();
            return zh.Length > 0 ? zh : null;
        }
        catch { return null; }
    }
}
